flutter/buy_idea/lib/component/account/sign_up_id_text_form.dart
flutter/buy_idea/lib/pages/account/consumer_sign_up_page.dart

feat: [진건오] 일반회원용 회원가입 페이지[DIY-SALES-APP-UI 2]

---

flutter/buy_idea/lib/component/account/login_form.dart
flutter/buy_idea/lib/component/account/text_form_field.dart
flutter/buy_idea/lib/pages/account/login_page.dart
flutter/buy_idea/lib/utility/validation.dart

가입한 사용자가 사이트에 로그인하기 위한 로그인 페이지UI [DIY-SALES-APP-UI 8]
~~ 진행중 ~~~
1. loginform
2. textformfield
3. loginpage
4. validation(아이디 패스워드)
5. 회원가입버튼
-----
일반회원 로그인과 판매자 로그인 선택 진행중

feat:[김소연] 가입한 사용자가 사이트에 로그인하기 위한 로그인 페이지UI [DIY-SALES-APP-UI 8]

---

vue/frontend/src/App.vue
vue/frontend/src/components/account/SignInForm.vue
vue/frontend/src/views/account/SignInView.vue

항목
- 기본적인 UI 틀 작업
- App.vue 로그인 페이지 라우터 연결 및 회원가입 페이지 라우터 연결

feat: [박선호] 로그인하기 위한 로그인 페이지 UI [DIY-SALES-WEB-UI 7]

---

flutter/buy_idea/lib/api/spring_member_api.dart
flutter/buy_idea/lib/component/account/Member.dart

feat:[김소연] 사용자가 로그인 버튼을 눌렀을 때 서버로 로그인 요청을 보내는 시스템[DIY-SALES-APP-UI 10]

---

flutter/buy_idea/lib/component/appBar/common_app_bar.dart
flutter/buy_idea/lib/component/common/account/sign_up_form_field.dart
flutter/buy_idea/lib/main.dart
flutter/buy_idea/lib/pages/account/consumer_sign_up_page.dart
flutter/buy_idea/lib/pages/account/login_page.dart
flutter/buy_idea/lib/pages/account/select_sign_up_page.dart
flutter/buy_idea/lib/pages/account/seller_sign_up_page.dart

- main.dart
- ThemeData삭제 -> 아직 사용하는 곳이 없어 불필요한 코드로 인식
- 회원가입 공통 컴포넌트 일부 코드 변경
-  변경 백로그
- [DIY-SALES-APP-UI 2]
- [DIY-SALES-APP-UI 3]
- 뒤로가기 버튼 추가 백로그
- [DIY-SALES-APP-UI 8]
- [DIY-SALES-APP-UI 9]
- [DIY-SALES-APP-UI 2]

feat: [진건오] main 파일 코드 수정

---

python/test.ipynb
spring/buy_idea/src/main/java/team_project/buy_idea/controller/member/BuyDiaMemberController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/member/Authentication.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/member/BasicAuthentication.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/member/BuyDiaMember.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/member/AuthenticationRepository.java

authentication
basicAuthentication
buyDiaMember
커밋을 빠뜨려서 다시 커밋함.

feat:[임재범] 비밀번호 암호화하여 저장하는 시스템 - 재커밋 [DIY-SALES PROCESS 4]

---

flutter/buy_idea/lib/api/spring_member_api.dart
flutter/buy_idea/lib/component/common/account/sign_up_form_field.dart
flutter/buy_idea/lib/component/common/account/sign_up_id_text_form.dart
flutter/buy_idea/lib/component/common/account/sign_up_nickname_text_form.dart
flutter/buy_idea/lib/pages/account/consumer_sign_up_page.dart
flutter/buy_idea/lib/pages/account/seller_sign_up_page.dart

- 아이디 중복 확인 API 설계
- 닉네임 중복 확인 API 설계
- 각각 중복확인 버튼클릭 시 요청 할 수 있도록 연결
- 사용자가 입력한 아이디와 닉네임이 잘 넘어오는지 확인
- 스프링과 연동이 잘 됐는지 확인

feat: [진건오] 회원가입 관련 API[DIY-SALES-APP-UI 12][DIY-SALES-APP-UI 14]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/member/MemberController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/member/Member.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/member/MemberRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/member/MemberService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/member/MemberServiceImpl.java

feat: [조안나] spring naming modify

---

flutter/buy_idea/lib/component/account/sign_up/sign_up_form.dart
flutter/buy_idea/lib/component/account/sign_up/sign_up_id_text_form.dart
flutter/buy_idea/lib/component/account/sign_up/sign_up_nickname_text_form.dart
flutter/buy_idea/lib/component/account/sign_up/sign_up_password_text_form.dart
flutter/buy_idea/lib/component/common/common_alert_dialog.dart

**완료**
✅ 아이디, 상호명 중복체크 확인 여부 
✅ 중복 확인 결과
✅ 회원가입 성공 여부

feat: [조안나] 사용자가 회원가입시 안내 받아야할 정보를 AlertDialog창으로 안내하는 시스템 [DIY-SALES-APP-UI 16]

---

vue/frontend/src/App.vue
vue/frontend/src/views/account/SignInView.vue

- app.vue 파일 일부 코드 수정
- 로그인 세션 유지
- 로그인 후 상단 헤더에 로그인, 회원가입 버튼이 
로그아웃, 마이페이지로 변경됨
- 로그아웃 기능

feat: [진건오] 사용자가 로그인 했을 때 변경되는 상단 헤더 UI [DIY-SALES-WEB-UI 6]

---

vue/frontend/src/App.vue
vue/frontend/src/components/MainPageForm.vue
vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/states.js
vue/frontend/src/views/account/SignInView.vue

- 로그인시 아이디 또는 비밀번호를 틀릴경우 알려주는 alert 추가
- history.go()로 인한 state 값이 초기화 되는 현상 수정
- 카테고리별 더보기 버튼 추가
- 카테고리별 상품 출력해주는 코드 중복 제거

fix: [진건오] 로그인시 사용자 정보 유지 및 로그인 시스템 변경, 메인페이지 UI 수정[DIY-SALES-WEB-UI 23][DIY-SALES-WEB-UI 24]

---

vue/frontend/src/App.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/HomeView.vue
vue/frontend/src/views/account/SignInView.vue

- 일부 수정을 하였지만 로그인을 유지못하는 이슈가 발생
-> 로직 수정

refactor: [진건오] 로그인 유지 로직 수정[DIY-SALES-WEB-UI 23]

---

flutter/buy_idea/lib/component/seller/my_info/seller_information.dart
flutter/buy_idea/lib/pages/seller/my_info/seller_my_info_page.dart
flutter/buy_idea/lib/pages/seller/seller_main_page.dart

항목
- 내 정보 페이지에 판매자 닉네임 표기
- 내 정보 페이지에 로그아웃 버튼 구현

feat: [박선호] 판매자가 내 정보 페이지에서 로그아웃을 할 수 있는 버튼 UI  [DIY-SALES-APP-UI 29]

---

python/SaveFileFromDB.ipynb
python/member_info_data.csv
python/python_branch_test.txt

**파이선 브랜치 생성 테스트** 
개인저장소에서 PR

test: [조안나] create python branch test

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/request/ProductRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductImage.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductImageRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/member/MemberTest.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/ProductTestCase.java

**완료**
✅ 상품 엔티티 (product, product_info, product_image)
✅ 상품 등록(본문,이미지) 서비스
✅ 테스트 완료

feat: [조안나] 판매자가 상품 등록 요청을 했을 때 DB에 상품 정보를 저장하는 시스템 [DIY-SALES-PROCESS 8]

---

flutter/buy_idea/pubspec.yaml

항목
- pubspec.yaml 에 bootpay 라이브러리 추가

feat: [박선호] 상품 결제를 위한 bootpay 라이브러리 설치 [DIY-SALES-APP-UI 41]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductInfo.java

**수정**
✅ Product info Entity content 글자수 제한 상향
✅ controller에서 RequestPart value name (vue랑 통일)

fix: [조안나] 판매자가 상품 등록 요청을 했을 때 DB에 상품 정보를 저장하는 시스템 [DIY-SALES-PROCESS 8]

---

vue/frontend/src/components/product/ProductRegisterForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/product/ProductRegisterView.vue

서버로 상품 등록 요청을 보내는 시스템
변경사항 
- actions -axios
- ProductRegisterForm
- ProductRegisterView

feat: [김소연] 판매자가 상품 등록을 눌렀을때 서버로 상품 등록요청을 보내는 시스템 [DIY-SALES-WEB-UI 30]

---

vue/frontend/src/store/actions.js
vue/frontend/src/views/product/ProductRegisterView.vue

**로그인**
- 판매자회원 로그인시 판매자페이지로 이동 추가
**수정사항**
- 상품등록시 판매자 상품관리페이지로 이동

add: [김소연] 사용자가 로그인 버튼을 눌렀을 때 서버로 로그인 요청을 보내는 시스템 [DIY-SALES-WEB-UI 12]

---

spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductImage.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java

**UPDATE**
✅ product entity column 추가(iamge path vue / flutter 구분)
✅ DB에 경로 각각 저장
✅ vue, flueet assets 각각 업로드

update: [조안나] 상품 등록 요청이오면 DB에 상품 정보를 저장하는 시스템 [DIY-SALES-PROCESS 8]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/Address.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/OrderInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/OrderInfoRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java

▶주문내역을 DB에 저장하는 시스템 구현 중 코드를 인계함.

코드인계:[임재범] 주문엔티티 일부 코드 인계 [DIY-SALES-PROCESS 15]

---

flutter/buy_idea/lib/component/account/sign_in/sign_in_form.dart
flutter/buy_idea/lib/component/account/sign_in/sign_in_text_form.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_info_card.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_info_list_tile_form.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_info_list_tile_widget.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_information.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_info_page.dart

**완료**
✅ 일반회원 내 정보 페이지 UI 구현
✅ 비회원 내 정보 페이지 UI 구현 
✅ 로그인 페이지에서 비밀번호 입력시 기호화 되도록 수정
✅ 로그인 후 페이지 이동시 앱바 뒤로가기 버튼 비활성화

feat: [조안나] 일반회원이 마이페이지를 클릭했을 때 보여지는 회원정보/관리 페이지 UI [DIY-SALES-APP-UI 17]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/ProductTestCase.java

항목
- 넘어온 상품 게시물 번호와 일치하는 상품의 정보들을 반환
- 넘어온 상품 게시물의 번호와 일치하는 상품의 이미지 리스트 반환
- 서비스 로직 테스트

feat: [박선호] 상품의 정보들을 반환해주는 시스템 [DIY-SALES-PROCESS 21]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/AddressRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/OrderInfoRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/Address.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/OrderInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/AddressRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/OrderTestCase.java

**일반회원이 주문한 주문내역을 DB에 저장하는 시스템 [DIY-SALES-PROCESS 15]**
✔️일반회원이 상품을 주문하면 주문내역이 DB에 저장
✔️상품 주문시 입력받은 배송정보가 DB에 저장
✔️Controller Request Entity Repository Service ServiceImpl
✔️Test
- orderDate 는 들어오는 시점에 스프링에서 저장

feat: [김소연] 일반회원이 주문한 주문내역을 DB에 저장하는 시스템 [DIY-SALES-PROCESS 15]

---

flutter/buy_idea/lib/api/spring_product_api.dart

항목
- 첫 번째 상품 리스트 요청
- 다음 상품 리스트 요청
- 상품 썸네일 이미지 요청

feat: [박선호] 카테고리별 상품 리스트를 요청하는 시스템 [DIY-SALES-APP-UI 50]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/ShoppingBucketController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/request/ShoppingBucketRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucket.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucketItem.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/shopppingBucket/ShoppingBucketProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/shopppingBucket/ShoppingBucketRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/shoppingBucket/ShoppingBucketTest.java

- 장바구니 시스템
- 장바구니에 상품 저장 시스템[DIY-SALES-PROCESS 18]
- 장바구니에 저장된 상품 전달 시스템[DIY-SALES-PROCESS 19]

feat: [진건오] 장바구니 시스템[DIY-SALES-PROCESS 18]

---

flutter/buy_idea/lib/api/spring_member_api.dart
flutter/buy_idea/lib/component/account/member.dart
flutter/buy_idea/lib/component/buyer/app_bar/no_logo_top_bar.dart
flutter/buy_idea/lib/component/buyer/app_bar/title_top_bar.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_info_list_tile_form.dart
flutter/buy_idea/lib/component/buyer/my_info/company_info_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_info_modify/my_profile_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_info_modify/nickname_modify_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_info_modify/password_modify_form.dart
flutter/buy_idea/lib/component/common/yes_or_no_alert_dialog.dart
flutter/buy_idea/lib/pages/buyer/category/handmade_page.dart
flutter/buy_idea/lib/pages/buyer/category/hobby_page.dart
flutter/buy_idea/lib/pages/buyer/category/knowhow_page.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_info_modify_page.dart
flutter/buy_idea/lib/pages/buyer/my_info/service_center_page.dart

**완료**
✅ 일반회원의 회원탈퇴
✅ 일반회원의 닉네임 수정
✅ 로고 없는 app bar (페이지 연결 O)
✅ 내 정보 페이지 
✅ 고객센터 페이지

feat: [조안나] 일반회원의 회원탈퇴 / 닉네임 수정[DIY-SALES-APP-UI 51] [DIY-SALES-APP-UI 45]

---

flutter/buy_idea/lib/component/buyer/product/product_buy_and_shopping_cart_select_modal_sheet.dart

항목
- 장바구니와 구매하기 클릭 시 로그인한 사용자만 해당 서비스를 이용할 수 있도록 로직 추가

update: [박선호] 구매 모달 창 UI 로그인 확인 로직 추가 [DIY-SALES-APP-UI 32]

---

vue/frontend/src/components/orderStatus/OrderStatusChangeButton.vue
vue/frontend/src/components/seller/OrderManageForm.vue

remove: [임재범] 판매자 주문관리 페이지 UI [DIY-SALES-WEB-UI 16]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductImageRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductInfoRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/ProductTestCase.java

**판매자가 상품 수정 요청시 DB에 저장된 상품 정보를 수정하는 시스템[DIY-SALES-PROCESS 22]**
✔️**수정된 사항**
ProductController -modify 추가
ProductImageRepository -기존 사진 삭제 쿼리추가
ProductService,Impl modify 추가
✔️**추가된 사항**
ProductInfoRepository 추가생성
✔️**상품 수정 테스트 완료**
ProductTestCase 
**판매자가 상품 삭제 요청시 DB에 저장된 상품 정보를 삭제하는 시스템[DIY-SALES-PROCESS 23]**
✔️수정사항
product controller remove 추가
productInfo repository 추가
product service, impl 추가
test

feat: [김소연] 판매자가 상품 수정 요청시 DB에 저장된 상품 정보를 수정하는 시스템[DIY-SALES-PROCESS 22]

---

spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
vue/frontend/src/components/ShoppingCart/ShoppingCartForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/states.js
vue/frontend/src/views/shoppingCart/ShoppingCartView.vue

- 상품 데이터 받는 로직 변경
- 상품 수량에 따른 배송비 변경 로직 변경
- 체크된 상품들의 가격 및 배송비 계산
- product엔티티와 연관관계를 가진 productImages 컬럼의 @JsonIgnore 어노테이션 삭제

chore: [진건오] 일반회원 장바구니 상품 리스트 확인 UI[DIY-SALES-WEB-UI 38]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/SellerInfo/SellerInfoReceiveController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/SellerInfo/request/SellerInfoRequestData.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/request/OrderInfoRequest.java
vue/frontend/src/components/seller/OrderManageForm.vue
vue/frontend/src/components/seller/SellerInfoForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/seller/SellerInfoView.vue

[DIY-SALES-WEB-UI-16]
▶상단에 고정된 닉네임을 표시하던 것에서
현재 로그인 중인 판매자회원의 상호명이 표시되는 것으로 변경함.
[DIY-SALES-WEB-UI-8, 32]
▶판매자 로그인 후 사업자 등록 페이지 UI와 사업자 등록정보 입력 후 그 데이터들을 spring에 보내는 것 까지 완료함.
▶스프링 Request와 Controller를 누락하여 커밋하는 이슈 발생하여 add로 추가 커밋을 진행함.

add: [임재범] 판매자 주문관리 페이지 UI [DIY-SALES-WEB-UI 16]

---

vue/frontend/src/components/product/ProductModifyForm.vue
vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/router/index.js
vue/frontend/src/views/product/ProductModifyView.vue

✔️배송비 5만원 이상 무료배송 추가
✔️총가격 설정 추가
✔️판매자용 수정/삭제 아이콘 추가
-알림창 추가

add: [김소연] 일반회원/비회원이 상품을 클릭했을때 상품 상세 정보 페이지의 판매정보 UI [DIY-SALES-WEB-UI 14]

---

flutter/buy_idea/lib/component/buyer/order/delivery_address_input_form.dart
flutter/buy_idea/lib/component/buyer/order/ordering_customer_info_form.dart
flutter/buy_idea/lib/pages/buyer/order/order_page.dart
flutter/buy_idea/pubspec.yaml

항목
- 주문 페이지 UI
- 주문 페이지 주문 고객 정보 Form UI
- 주문 페이지 배송지 입력 Form UI
- KOPO 라이브러리 추가

feat: [박선호] 주문 페이지 주문 고객 정보, 배송지 입력 UI [DIY-SALES-APP-UI 6]

---

vue/frontend/src/components/category/CategoryForm.vue

- 상품 리스트 card UI 변경
- 카테고리별 더보기 버튼 위치 및 색상 변경

update: 모든 사용자가 페이지 접속 시 보여지는 메인페이지 UI [DIY-SALES-WEB-UI 17]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/ShoppingBucketController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/request/ShoppingBucketRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/shopppingBucket/ShoppingBucketProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/shopppingBucket/ShoppingBucketRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/shoppingBucket/ShoppingBucketTest.java

- 장바구니 조회 시 사용자 토큰값 전달❌ -> 사용자 닉네임으로 변경
- 장바구니 상품 추가시 사용자 토큰값❌ -> 사용자 닉네임으로 변경

fix: [진건오] 일반회원 사용자가 장바구니 시스템[DIY-SALES-PROCESS 19]

---

vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/shoppingCart/ShoppingCartView.vue

- 스프링에서 장바구니 저장 및 상품리스트 요청 로직 변경으로 인해
vue에서 장바구니 상품 요청 axios 변경
- 메인페이지에서 상품 클릭시 해당 상품 번호를 넘겨주기 위해 a태그에서 router-link 태그로 변경

[진건오] 장바구니 시스템 및 메인페이지 UI  변경[DIY-SALES-WEB-UI 38][DIY-SALES-WEB-UI 17]

---

vue/frontend/src/components/ShoppingCart/ShoppingCartForm.vue
vue/frontend/src/components/order/OrderForm.vue
vue/frontend/src/router/index.js

- 장바구니에서 상품 선택 후 구매하기 버튼을 누르면 
주문페이지로 이동하고 주문페이지에는 장바구에서 선택한 상품이 존재하도록 구현
- 장바구니에서 선택한 상품을 받기위해
v-for문을 사용하고 상품들의 정보를 출력하기 위해
상품정보 표시 부분 수정

[진건오] 장바구니 상품 구입[DIY-SALES-WEB-UI 41][DIY-SALES-WEB-UI 5]

---

spring/buy_idea/src/main/java/team_project/buy_idea/service/order/request/OrderInfoRequest.java

remove: [김소연] 일반회원이 주문한 주문내역을 DB에 저장하는 시스템 [DIY-SALES-PROCESS 15]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/ShoppingBucketController.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/shoppingBucket/ShoppingBucketTest.java
vue/frontend/src/components/ShoppingCart/ShoppingCartForm.vue
vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/store/actions.js

- 이전에 메인페이지 상품리스트 UI를 변경하였는데 
핸드메이드 쪽만 변경이 되어 나머지 노하우, 취미/특기 부분도 변경

chore: [진건오] 메인페이지 UI [DIY-SALES-WEB-UI 17

---

flutter/buy_idea/lib/api/spring_order_api.dart
flutter/buy_idea/lib/component/buyer/order/delivery_address_input_form.dart
flutter/buy_idea/lib/component/buyer/order/ordering_info_form.dart
flutter/buy_idea/lib/pages/buyer/order/order_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/OrderRegisterRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java

항목 [DIY-SALES-PROCESS 25]
- @RequestPart로 json만을 받을 수가 없어서 @RequestBody로 받기 위해 기존의 AddressRequest와 OrderInfoRequest를 포함한 OrderRegisterRequest 생성
- 그에 따른 OrderController에서 @RequestPart로 두개를 받던걸 @RequestBody로 수정
- 주문 등록 서비스 로직 중에서 orderNo을 구하는 과정에서 DB에 등록되어있는 주문이 없다면
maybeOrderInfo가 null이 되는 상황 발생 그로 인해 lastOrderNo을 구할 수 없어
if (mayOrderInfo != null) 조건문 안쪽에 해당 로직 배치

update: [박선호] 주문번호를 생성하는 시스템 수정 [DIY-SALES-PROCESS 25]

---

vue/frontend/src/components/product/ProductModifyForm.vue
vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/product/ProductModifyView.vue

**판매자가 상품 수정 버튼을 눌렀을 때 서버로 상품 수정요청을 보내는 시스템[DIY-SALES-WEB-UI 44]**
✔️product modify form / view 수정
✔️axios
✔️ProductReadForm 수정/삭제 버튼 해당 판매자만 보이도록 변경
**판매자가 상품 삭제 버튼을 눌렀을 때 서버로 상품 삭제요청을 보내는 시스템[DIY-SALES-WEB-UI 45]**
✔️ product read form / view 수정
✔️ axios

feat: [김소연] 판매자가 수정버튼을 눌렀을때 서버로 상품 수정요청을 보내는 시스템[DIY-SALES-WEB-UI 44]

---

vue/frontend/src/views/shoppingCart/ShoppingCartView.vue

- 장바구니 상품 리스트 반환 axios  매개값을 사용자 아이디가 아닌 사용자 닉네임으로 변경

fix: [진건오] 장바구니 상품 리스트 요청 [DIY-SALES-WEB-UI 38]

---

vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/store/actions.js

feat: [진건오] 일반회원 사용자 장바구니 상품 추가 시스템 [DIY-SALES-WEB-UI 49]

---

vue/frontend/src/App.vue
vue/frontend/src/components/MainPageForm.vue
vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/components/productByCategory/ProductByCategoryForm.vue
vue/frontend/src/components/shoppingCart/ShoppingCartForm.vue
vue/frontend/src/router/index.js
vue/frontend/src/views/productByCategory/HandmadeCategoryView.vue
vue/frontend/src/views/productByCategory/HobbyCategoryView.vue
vue/frontend/src/views/productByCategory/KnowhowCategoryView.vue

- 카테고리별 상품 페이지
- 장바구니에서 상품 선택 후 구매페이지로 이동 시 총 금액이 안맞는 경우
또 배송비가 제대로 계산되지 않는 경우
- 메인페이지 카테고리별 상품 리스트 이미지 호출 시 나타났던 이슈 해결

[진건오] 상품 리스트 [DIY-SALES-WEB-UI 48][DIY-SALES-WEB-UI 41][DIY-SALES-WEB-UI 42]

---

vue/frontend/src/components/order/OrderForm.vue
vue/frontend/src/components/product/ProductReadForm.vue

**update**
-바로결제 버튼을 눌렀을때 상품 정보와 가격 배송비가 결제창에 넘어가도록 설정
**chore**
-장바구니에서 넘겨받은 상품정보와 바로결제에서 넘겨받은 상품정보를 구분해 띄우도록 조건 설정

update: [김소연] 사용자가 상품을 클릭했을 때 보여지는 상품 상세 정보 페이지의 판매정보 UI [DIY-SALES-WEB-UI 14]

---

flutter/buy_idea/pubspec.yaml

항목
- 구매 후기 등록 시 이미지 업로드를 위한 Image Picker 라이브러리 추가
- 구매 후기 등록 시 별점을 매기기 위한 Flutter Rating Bar 라이브러리 추가

feat: [박선호] Image Picker, Flutter Rating Bar 라이브러리 추가 [DIY-SALES-APP-UI 70][DIY-SALES-APP-UI 71]

---

vue/frontend/src/components/category/CategoryForm.vue

- 메인페이지 접속시 카테고리별 상품 리스트 사이즈 변경
- 상품에 마우스 커서를 올렸을 시 hover 활성화
- 카테고리별 상품 더보기 버튼 페이지 연결

update: [진건오] 메인페이지 UI [DIY-SALES-WEB-UI 17]

---

vue/frontend/src/components/seller/ProductManageForm.vue

▶상품 제목을 잘 보이도록 밖으로 빼냄
▶상품 등록 버튼 스크롤 해도 우측 하단에 따라다니도록 변경

update: [임재범] 판매자메뉴의 판매상품 관리 UI [DIY-SALES-WEB-UI 20]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/OrderInfoRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/OrderInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/OrderTestCase.java
vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue

**수정사항**
**[[DIY-SALES-PROCESS 15]**
price, seller, title 대신 procutNo를 넘겨줘서 product에서 정보를 가져올 수 있도록 수정
- OrderInfoRequest 수정 
- OrderInfo entity 수정
- OrderInfo ServiceImpl 수정
- Test
- FetchType.LAZY로 수정
**사용자가 상품결제를 요청했을때 상품재고에서 주문한 수량을 빼는 시스템[DIY-SALES-PROCESS 27]**
- OrderInfo ServiceImpl
**add [DIY-SALES-WEB-UI 34]**
- 주문 상태 chip 추가 
- 주문 상태에 따른 후기/배송조회 조건 
- 배송 조회 버튼 배송조회 페이지 연결
- 상세 주문페이지 연결

chore: [김소연] 일반회원이 주문한 주문내역을 DB에 저장하는 시스템 [DIY-SALES-PROCESS 15]

---

flutter/buy_idea/pubspec.yaml

feat: [박선호] 서버로 이미지 전송을 위한 Dio 라이브러리 추가 [DIY-SALES-APP-UI 78]

---

spring/buy_idea/src/main/java/team_project/buy_idea/entity/member/Member.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/Address.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucket.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucketItem.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductImage.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/member/MemberRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/shopppingBucket/ShoppingBucketProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/shopppingbucket/ShoppingBucketServiceImpl.java

**[entity 수정]**
[**repository 수정]**

feat: [김소연] Entity fetch 방식 LAZY로 변경 및  jpql 코드보완[DIY-SALES-PROCESS 29]

---

flutter/buy_idea/lib/component/buyer/my_info/buyer_info_card.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_information.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_info_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/my_order_info_page.dart

**완료**
✅ 주문/배송 페이지 UI 
✅ 내 정보 페이지 주문 배송 버튼에  페이지 연결

feat: [조안나] 일반회원이 주문배송 페이지에서 볼 수 있는 결제한 상품 리스트 UI [DIY-SALES-APP-UI 75]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/ReviewController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/request/ReviewRegisterRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/review/Review.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/review/ReviewImage.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewImageRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/review/ReviewTestCase.java

feat: [박선호] 상품 구매 후기 등록 시스템 [DIY-SALES-PROCESS 26]

---

flutter/buy_idea/lib/api/spring_review_api.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/review/review_register_text_field_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/review/review_register_page.dart

항목
- 상품 구매 후기 등록 api
- 상품 구매 후기 등록 페이지 UI

feat: [박선호] 구매 후기 등록 api [DIY-SALES-APP-UI 77]

---

vue/frontend/src/components/order/OrderForm.vue
vue/frontend/src/components/shoppingCart/ShoppingCartForm.vue
vue/frontend/src/store/actions.js

- 결제 진행 후 결제 완료시 주문정보를 서버로 전송해주는 시스템 구현

feat: [진건오] 상품 결졔 후 결제정보를 보내주는 시스템 [DIY-SALES-WEB-UI 50]

---

vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/router/index.js
vue/frontend/src/views/buyerMyPage/OrderDetailView.vue

**[DIY-SALES-WEB-UI 37]**
해당 주문에 대한 주문상품목록, 배송정보, 결제정보를 볼 수 있는 주문상세보기 UI 
추가사항
변경사항

feat: [김소연] 일반회원이 최근주문내역에서 주문을 클릭하면 볼 수 있는 주문상세보기 UI [DIY-SALES-WEB-UI 37]

---

flutter/buy_idea/lib/api/spring_review_api.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/ReviewController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewImageRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/mapping/ReviewImageMapping.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/review/ReviewTestCase.java

항목
- 상품 후기 리스트 반환
- 다음 후기 리스트 반환
- 상품 후기 이미지 반환

feat: [박선호] 상품 후기 리스트 반환 시스템 [DIY-SALES-PROCESS 31]

---

flutter/buy_idea/lib/api/spring_order_api.dart
flutter/buy_idea/lib/pages/buyer/order/order_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/Address.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/OrderInfoRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/OrderTestCase.java

**완료**
✅ 결제 엔티티 변경에 따른 App 결제 요청 시스템 수정
✅ Spring 주문 정보 리스트 반환 시스템

feat: [조안나] 일반회원이 주문 정보를 요청했을 때 해당 정보를 반환하는 시스템 [DIY-SALES-PROCESS 30]

---

spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java

**수정**
✅ order date 2023-01-07 11:55 형태로 저장되도록 수정하였음

update: [조안나] 사용자가 상품결제를 요청했을 때 결제정보를 저장하는 시스템[DIY-SALES-PROCESS 25]

---

flutter/buy_idea/lib/api/spring_review_api.dart
flutter/buy_idea/lib/component/buyer/product/product_details_page_header.dart
flutter/buy_idea/lib/component/buyer/product/review/product_review_form.dart
flutter/buy_idea/lib/pages/buyer/product/product_details_page.dart
flutter/buy_idea/pubspec.yaml
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/review/Review.java

항목
- product entity에 review 연관관계 설정
- review entity에 product 연관관계 설정

update: [박선호] 상품의 후기들을 반환하는 시스템 [DIY-SALES-PROCESS 31]

---

vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/components/seller/SellerNavi.vue

**add 일반회원이 주문상세보기를 클릭했을 때 상세정보을 UI에 매핑하는 시스템[DIY-SALES-WEB-UI 53]**
+결제정보의 상품명 숫자 글자 수 초과시 줄임표 추가 (filter)
+결제정보의 각 상품 가격/배송비 표시
+주문건에 대한 총 상품가격, 배송비, 최종금액 계산 표시
**판매자회원이 로그아웃 버튼을 눌렀을 때 저장된 토큰값을 지우는 시스템[DIY-SALES-WEB-UI 54]**
수정사항 
SellerNavi 로그아웃 버튼 추가
로그아웃 기능

add: [김소연] 일반회원이 주문상세보기를 클릭했을 때 상세정보을 UI에 매핑하는 시스템[DIY-SALES-WEB-UI 53]

---

flutter/buy_idea/lib/component/buyer/category/category_product.dart
flutter/buy_idea/lib/component/buyer/category/category_product_card.dart
flutter/buy_idea/lib/component/buyer/category/category_product_list_from.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_detail_info_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_info_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/order_status_set_string.dart
flutter/buy_idea/lib/pages/buyer/main_menu/search_list_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/OrderInfoRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/request/OrderStatusModifyRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/OrderInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/OrderStatus.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/OrderTestCase.java

**완료**
✅ App 상품리스트 카드 UI에 리뷰평점, 개수 매핑
✅ Spring 주문 상태 enum 변경
✅ Spring 주문 상태 enum 변경으로 인한 결제 정보 저장시스템 수정
✅ Spring 주문 상태 변경 시스템
✅ App 주문 상태 변경으로 인한 UI 매핑 시스템 수정

feat: [조안나] 상품리스트 상품 카드UI에 리뷰평점과 리뷰개수를 매핑하는 시스템[DIY-SALES-APP-UI 85]

---

flutter/buy_idea/lib/api/spring_review_api.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/ReviewController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/request/ReviewModifyRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/review/Review.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewImageRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/review/ReviewTestCase.java

**[DIY-SALES-PROCESS 34]**
**[DIY-SALES-PROCESS 35]**
**[DIY-SALES-APP-UI 87]**
**[DIY-SALES-APP-UI 88]**

feat: [박선호] 상품 구매 후기 수정 시스템 [DIY-SALES-PROCESS 34]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/components/order/OrderForm.vue

-주문 상태 enum으로 관리로 변경함에 따른 수정
**변경사항**
- orderForm 
- BuyerMyPageForm 
- OrderDetailForm

add2: [김소연] 일반회원이 주문상세보기를 클릭했을 때 상세정보을 UI에 매핑하는 시스템[DIY-SALES-WEB-UI 53]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue

**변경사항**
문의 등록 dialog
- BuyerMyPageForm
- OrderDetailForm

feat: [김소연] 일반회원이 주문내역에서 상품에 대한 문의를 등록할 수 있는 UI[DIY-SALES-WEB-UI 35]

---

flutter/buy_idea/lib/api/spring_qna_api.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/question_register_bottom_button.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/question_register_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_detail_info_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/QnA/question_register_page.dart
flutter/buy_idea/pubspec.yaml
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/QnAController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/request/QuestionRegisterRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/qna/AnswerStatus.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/qna/QnA.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/qna/QuestionCategory.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/qna/QnARepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/qna/QnATestCase.java

**완료**
✅ App 주문 상세정보 페이지 UI 변경
✅ App 문의 등록 페이지 UI
✅ Spring QnA Entity 생성 & 문의 글 등록 시스템
✅ App 문의 글 등록 요청 API

feat: [조안나] 일반회원이 작성한 문의 글 등록을 요청하는 API [DIY-SALES-APP-UI 90]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/store/actions.js

feat: [김소연] 일반회원이 문의등록 버튼을 클릭했을 때 서버로 요청을 보내는 시스템[DIY-SALES-WEB-UI 56]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue

- methods에 actions에서 작동되는 리뷰 메서드 정의 
- 리뷰 작성 후 다시 마이페이지로 돌아가도록 설정

fix: [진건오] 리뷰 시스템 누락된 코드 [DIY-SALES-WEB-UI 51]

---

flutter/buy_idea/lib/api/spring_review_api.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/review/review_modify_text_field_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/review/review_modify_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/review/ReviewController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/review/ReviewRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/ReviewServiceImpl.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/review/response/MyReviewResponse.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/review/ReviewTestCase.java

**[DIY-SALES-PROCESS 37]**
**[DIY-SALES-APP-UI 92]**
**[DIY-SALES-APP-UI 91]**
**[DIY-SALES-PROCESS 38]**
**[DIY-SALES-APP-UI 96]**

feat: [박선호] 특정 일반회원 상품 구매 후기 리스트 반환 시스템 [DIY-SALES-PROCESS 37]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue

**수정사항**
리뷰 작성 후 모달 창을 벗어나도록 하는 방식 변경
dialog 값을 false로 변경하여 등록 후 꺼지도록 설정

fix: [김소연] 일반회원이 문의 등록을 했을 때 서버로 문의 등록 요청을 보내는 시스템[DIY-SALES-WEB-UI 56]

---

flutter/buy_idea/lib/component/buyer/my_info/buyer_information.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/review/my_review_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/review/my_review_page.dart

feat: [박선호] 일반회원 나의 후기 페이지 UI [DIY-SALES-APP-UI 97]

---

vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/components/product/qna/QnaForm.vue

feat: [김소연] 일반회원이 상품상세정보페이지에서 상품문의를 클릭했을때 나오는 리스트 UI[DIY-SALES-WEB-UI 31]

---

vue/frontend/src/components/productByCategory/HandmadeProductByCategoryForm.vue

- handmadeProductByCategoryForm 추가 커밋

feat: [진건오] 카테고리별 상품리스트 스크롤 페이징 설정 누락사항 [DIY-SALES-WEB-UI 57]

---

flutter/buy_idea/lib/api/spring_qna_api.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/my_question_history_card.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/my_question_history_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/my_question_history_info.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/question_register_bottom_button.dart
flutter/buy_idea/lib/component/buyer/product/QnA/product_open_qna_card.dart
flutter/buy_idea/lib/component/buyer/product/QnA/product_private_qna_card.dart
flutter/buy_idea/lib/component/buyer/product/QnA/product_qna_form.dart
flutter/buy_idea/lib/component/buyer/product/QnA/qna_register_card.dart
flutter/buy_idea/lib/pages/buyer/product/product_details_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/QnAController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/qna/QnARepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAServiceImpl.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/response/QnaHistoryResponse.java

**완료**
✅ App 상품에 관한 문의내역 요청 API
✅ Spring 상품에 관한 문의내역 요청시 문의 리스트 반환
✅ App 상품 상세정보 페이지에서의 문의 UI
✅ App 문의글 삭제 요청 API
✅ Spring 문의글 삭제 시스템
✅ 문의글 등록 완료후 해당 상품 상세페이지로 이동하도록 수정

feat: [조안나] 문의글 삭제 요청이 왔을 때 해당 문의글을 DB에서 삭제하는 시스템 [DIY-SALES-PROCESS 41]

---

vue/frontend/src/App.vue
vue/frontend/src/components/MainPageForm.vue
vue/frontend/src/components/footer/FooterForm.vue
vue/frontend/src/views/productByCategory/HandmadeCategoryView.vue
vue/frontend/src/views/productByCategory/HobbyCategoryView.vue
vue/frontend/src/views/productByCategory/KnowhowCategoryView.vue

- footer UI 구현
- 메인페이지 카테고리별 상품 출력 개수 5개 -> 8개로 수정
- 카테고리별 페이지 스크롤 시 대기시간 1초 -> 2초로 변경

feat: [진건오] 페이지 footer UI [DIY-SALES-WEB-UI 59]

---

flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_detail_info_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/my_order_info_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/QnA/question_register_page.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/my_order_info_page.dart

**완료**
✅ 문의 등록페이지에서 문의 내역 바로가기 페이지 연결
✅ 주문한 상품에 대해 리뷰를 작성한 건이 있으면 리뷰버튼 비활성화

feat: [조안나] 이미 리뷰를 작성했을 시 리뷰등록 버튼 비활성화되는 시스템 [DIY-SALES-APP-UI 103]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageForm.vue
vue/frontend/src/components/buyerMyPage/BuyerQnaForm.vue
vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/store/actions.js

변경사항
+ 나의문의내역에서 문의 삭제 기능
+ 문의등록시 내 문의페이지로 이동하도록 변경
+ 로그인 유무에 따라 달라지는 상세페이지 문의하기 버튼

feat: [김소연] 일반회원이 문의내역에서 삭제 버튼을 눌렀을 때 삭제 요청을 보내는 시스템[DIY-SALES-WEB-UI 61]

---

vue/frontend/src/components/productByCategory/HandmadeProductByCategoryForm.vue
vue/frontend/src/components/productByCategory/HobbyProductByCategoryForm.vue
vue/frontend/src/components/productByCategory/KnowHowProductByCategoryForm.vue
vue/frontend/src/views/productByCategory/HandmadeCategoryView.vue
vue/frontend/src/views/productByCategory/HobbyCategoryView.vue
vue/frontend/src/views/productByCategory/KnowhowCategoryView.vue

feat: [진건오] 카테고리별 상품 페이지 상품 평점 [DIY-SALES-WEB-UI 66]

---

vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/components/product/review/ReviewForm.vue

feat: [김소연] 일반회원이 상품 상세 정보 페이지에서 볼 수 있는 구매후기 리스트UI[DIY-SALES-WEB-UI 32]

---

vue/frontend/src/components/buyerMyPage/BuyerNav.vue
vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue
vue/frontend/src/router/index.js
vue/frontend/src/views/buyerMyPage/BuyerReviewView.vue

feat: [진건오] 일반회원 사용자 본인이 작성한 리뷰를 볼 수 있는 페이지 [DIY-SALES-WEB-UI 68]

---

flutter/buy_idea/lib/component/seller/qna_management/AnswerRegisterBottomButton.dart
flutter/buy_idea/lib/component/seller/qna_management/answer_register_form.dart
flutter/buy_idea/lib/component/seller/qna_management/wait_for_answer_history_card.dart
flutter/buy_idea/lib/pages/seller/qna_management/answer_register_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/QnAController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/request/AnswerRegisterRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/qna/QnATestCase.java

**완료**
✅ App 답변 등록 페이지 UI
✅ Spring 답변 등록 시스템

feat: [조안나] 판매자가 문의 글 답변 등록을 요청하면 답변을 DB에 저장하는 시스템 [DIY-SALES-PROCESS 44]

---

flutter/buy_idea/lib/api/seller/spring_seller_qna_api.dart
flutter/buy_idea/lib/component/buyer/app_bar/title_top_bar.dart
flutter/buy_idea/lib/component/seller/qna_management/AnswerRegisterBottomButton.dart
flutter/buy_idea/lib/component/seller/qna_management/answer_complete_form.dart
flutter/buy_idea/lib/component/seller/qna_management/wait_for_answer_form.dart
flutter/buy_idea/lib/pages/seller/qna_management/qna_management_page.dart

**완료**
✅ App 등록 요청 시스템
✅ 일반회원 타이틀 앱바 글씨 크기 수정

feat: [조안나] 판매자가 작성한 답변 내용 등록을 요청하는 시스템 [DIY-SALES-APP-UI 111]

---

flutter/buy_idea/lib/api/seller/spring_seller_qna_api.dart
flutter/buy_idea/lib/component/seller/qna_management/answer_complete_form.dart
flutter/buy_idea/lib/component/seller/qna_management/answer_complete_history_card.dart
flutter/buy_idea/lib/component/seller/qna_management/wait_for_answer_form.dart
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/qna/QnAController.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/qna/QnAServiceImpl.java

**완료**
✅ Spring 답변 삭제 시스템
✅ App 답변 삭제 요청 시스템
✅ 답변 대기/ 답변 상태 페이지 문의글 없을 시 띄우는 문구 위치 수정

feat: [조안나] 판매자가 등록했던 답변 삭제 요청을 했을 때 답변 상태 변경과 답변 내용을 삭제하는 시스템[DIY-SALES-PROCESS 45]

---

flutter/buy_idea/lib/component/seller/app_bar/seller_drawer.dart
flutter/buy_idea/lib/pages/intro_screen_page.dart
flutter/buy_idea/lib/pages/seller/my_info/seller_my_info_page.dart
flutter/buy_idea/lib/pages/seller/product_registration_status/product_registration_status_page.dart
flutter/buy_idea/lib/pages/seller/qna_management/answer_register_page.dart
flutter/buy_idea/lib/pages/seller/qna_management/qna_management_page.dart
flutter/buy_idea/lib/pages/seller/seller_info.dart
flutter/buy_idea/lib/pages/seller/seller_main_page.dart

**완료**
✅ App 판매자 Drawer/bottom navigation 메뉴 전체 수정

update: [조안나] 사용자가 판매자로 로그인 시 모든 페이지에서 사용되는 Common App Bar UI [DIY-SALES-APP-UI 19]

---

vue/frontend/src/components/seller/QnaManageForm.vue

feat: [김소연] 판매자가 네비게이션에서 문의관리를 눌렀을때 나오는 문의관리 페이지 UI[DIY-SALES-WEB-UI 70]

---

vue/frontend/src/components/seller/QnaManageForm.vue
vue/frontend/src/store/actions.js

feat: [김소연] 판매자가 작성한 문의답변 내용 등록을 요청하는 시스템[DIY-SALES-WEB-UI 74]

---

vue/frontend/src/components/buyerMyPage/BuyerQnaForm.vue
vue/frontend/src/components/product/qna/QnaForm.vue

수정사항
fix) 답변과 등록되지 않았다는 문구가 둘 다 뜨는 이슈 수정

fix2: [김소연] 일반회원으로 로그인한 사용자가 본인이 쓴 문의를 볼 수 있는 UI[DIY-SALES-WEB-UI 58]

---

vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue
vue/frontend/src/store/actions.js

feat: [진건오] 마이리뷰 수정 [DIY-SALES-WEB-UI 77]

---

flutter/buy_idea/lib/api/seller/spring_seller_order_api.dart
flutter/buy_idea/lib/component/seller/app_bar/seller_drawer.dart
flutter/buy_idea/lib/component/seller/order_management/order_management_form.dart
flutter/buy_idea/lib/component/seller/order_management/order_status_list.dart
flutter/buy_idea/lib/component/seller/order_management/product_order_count_widget.dart
flutter/buy_idea/lib/component/seller/order_management/product_order_status_data.dart
flutter/buy_idea/lib/pages/seller/order_management/order_management_page.dart
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java

**완료**
✅ App 판매자 상품별 주문 개수 현황 요청 API -> 데이터 매핑 
✅ Spring 주문건수가 없는 상품은 반환하지 않도록 수정
✅ Drawer 후기관리 메뉴 삭제 / 주문 관리 -> 주문 현황 이름 변경

feat: [조안나] 판매자가 주문관리 페이지 접속시 주문현황 정보를 서버에 요청하는 API [DIY-SALES-APP-UI 118]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/OrderInfoController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/order/OrderInfoRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/order/OrderInfoServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/order/OrderTestCase.java

**[DIY-SALES-PROCESS 51]**
style
- 중복으로 작성되던 orderStatus 반환 코드를 method로 만들어 코드 스타일 수정

feat: [박선호] 특정 판매자가 매출 집계를 요청할 때 배송 완료된 주문건에 한하여 총 매출 금액을 반환하는 시스템 [DIY-SALES-PROCESS 51]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/seller/SellerController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/seller/SellerProfile.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/seller/SellerRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/seller/SellerService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/seller/SellerServiceImpl.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/seller/response/SellerInfoResponse.java
spring/buy_idea/src/test/java/team_project/buy_idea/seller/SellerTestCase.java

- 판매자 업체 정보 전달 시스템 구현
- 테스트 완료

feat: [진건오] 판매자 업체 정보 전달 시스템[DIY-SALES-PROCESS 52]

---

vue/frontend/src/components/seller/SellerInfoForm.vue
vue/frontend/src/components/seller/SellerNavi.vue
vue/frontend/src/store/actions.js
vue/frontend/src/views/seller/SellerInfoView.vue

feat: [진건오] 판매자 회원이 로그인 후 업체 정보를 등록할 수 있는 페이지 [DIY-SALES-WEB-UI 46]

---

flutter/buy_idea/lib/api/seller/spring_seller_total_api.dart
flutter/buy_idea/lib/component/seller/home/total_sales_form.dart
flutter/buy_idea/lib/pages/seller/seller_main_page.dart

**[DIY-SALES-APP-UI 120]**
**[DIY-SALES-APP-UI 122]**

feat: [박선호] 판매자가 로그인 후 이동되는 판매자 메인 페이지의 매출 집계 form UI [DIY-SALES-APP-UI 120]

---

vue/frontend/src/components/seller/SellerInfoForm.vue
vue/frontend/src/views/seller/SellerInfoView.vue

- 판매자 업체 정보 출력 
- 카카오 맵 API 사용

feat: [진건오] 판매자 업체 정보를 보여주는 UI[DIY-SALES-WEB-UI 84]

---

vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/components/product/ProductReadForm.vue

fix: [김소연] 로그인한 일반회원이 주문상세보기를 클릭했을 때 UI에 매핑하는 시스템[DIY-SALES-WEB-UI 53]

---

vue/frontend/src/components/seller/SellerMainPageForm.vue

▶Home 페이지에는 등록한 상품 개수, 등록된 구매 후기, 등록된 문의, 주문 총 개수, 총 매출을 표시함.
▶데이터 매핑은 아직 하지 않았고 UI만 진행함.

feat: [임재범] 판매자 로그인 후 바로 연결되는 판매자 Home 페이지 UI [DIY-SALES-WEB-UI 88]

---

vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue
vue/frontend/src/views/buyerMyPage/BuyerReviewView.vue

- 리뷰 삭제 시 원하는 리뷰가 아닌 다른 리뷰가 삭제되는 이슈 
→ 해결
- 리뷰 삭제 후 페이지 먹통 
→ 해결

fix: [진건오] 일반회원 리뷰 삭제 시스템[DIY-SALES-WEB-UI 78]

---

vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue
vue/frontend/src/views/buyerMyPage/BuyerReviewView.vue

- 리뷰는 잘 삭제되나 삭제 후 새로고침 시 남아있는 리뷰들의 사진이 
나타나지 않는 이슈 발견
→ 사진을 불러오는 axios를 form에서 실행하는 것이 아닌 view에서 실행하도록 변경
→ 해결

fix2: [진건오] 일반회원 리뷰 삭제 시스템[DIY-SALES-WEB-UI 78]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/Product.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/ProductInfo.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java

test: [김소연] 사용자가 필터 선택시 필터에 맞는 상품 리스트를 반환하는 시스템 [DIY-SALES-PROCESS 54]

---

vue/frontend/src/store/mutations.js

- 찜을 통해 상품을 저장하고난 뒤 다시 찜을 눌러 상품을 제거할 때
정상적으로 제거되지 않는 현상 해결

update2: [진건오] 메인페이지 카테고리별 상품 찜 기능 [DIY-SALES-WEB-UI 93]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/ProductController.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/ProductRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/ProductServiceImpl.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/ProductTestCase.java

feat: [박선호] 모든 사용자가 필터 선택시 선택한 필터에 맞는 상품 리스트를 반환하는 시스템 [DIY-SALES-PROCESS 54]

---

vue/frontend/src/components/MainPageForm.vue
vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/mutations.js

- 스프링 쪽 상품 불러오는 로직 변경으로 웹쪽 상품 불러오는 axios 변경
- 메인페이지에서 상품 찜하기 후 상세 페이지에서도 찜 여부를 확인 할 수 있도록 변경

fix: [진건오] 메인페이지 상품 불러오기 [DIY-SALES-WEB-UI 17]

---

vue/frontend/src/components/category/CategoryForm.vue
vue/frontend/src/components/product/ProductReadForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/mutations.js
vue/frontend/src/views/product/ProductReadView.vue

feat: [진건오] 상세페이지에서 상품 찜 시스템 [DIY-SALES-WEB-UI 94]

---

vue/frontend/src/components/buyerMyPage/BuyerFavoriteProductForm.vue
vue/frontend/src/components/buyerMyPage/BuyerNav.vue
vue/frontend/src/components/buyerMyPage/BuyerQnaForm.vue
vue/frontend/src/components/product/ProductReadForm.vue

마이페이지 통일감을 위한 이름 변경
상품 상세페이지 찜버튼 위치 변경

style: [김소연] 일반회원 사용자가 마이페이지에서 본인이 쓴 문의를 볼 수 있는 UI[DIY-SALES-WEB-UI 58]

---

flutter/buy_idea/lib/api/spring_favorite_api.dart
flutter/buy_idea/lib/component/buyer/my_info/buyer_information.dart
flutter/buy_idea/lib/component/buyer/my_info/my_favorite/my_favorite_form.dart
flutter/buy_idea/lib/component/buyer/my_info/my_favorite/my_favorite_product.dart
flutter/buy_idea/lib/component/buyer/my_info/my_favorite/my_favorite_product_card.dart
flutter/buy_idea/lib/component/buyer/my_info/my_order_info/QnA/my_question_history_form.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_favorite/my_favorite_page.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/QnA/my_question_history_page.dart
flutter/buy_idea/lib/pages/buyer/my_info/my_order_info/review/my_review_page.dart
flutter/buy_idea/lib/pages/buyer/product/favorite_controller.dart
flutter/buy_idea/lib/pages/buyer/product/product_details_page.dart
flutter/buy_idea/pubspec.yaml
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/favorite/FavoriteController.java
spring/buy_idea/src/main/java/team_project/buy_idea/controller/product/favorite/request/FavoriteRequest.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/favorite/Favorite.java
spring/buy_idea/src/main/java/team_project/buy_idea/repository/product/favorite/FavoriteRepository.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/favorite/FavoriteService.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/favorite/FavoriteServiceImpl.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/favorite/response/FavoriteResponse.java
spring/buy_idea/src/main/java/team_project/buy_idea/service/product/favorite/response/MyFavoriteListResponse.java
spring/buy_idea/src/test/java/team_project/buy_idea/product/favorite/FavoriteTestCase.java

**완료**
✅ App 상품 상세페이지에 찜 기능 
✅ App 내 정보 - 찜한 아이디어 UI + 리스트 요청 API 
✅ Spring 찜 저장/삭제/리스트 반환 
✅ 메뉴/앱바 타이틀/문구 style 수정

feat: [조안나] 일반회원이 찜한 상품을 조회시 찜한 상품 리스트를 반환하는 시스템 [DIY-SALES-PROCESS 57]

---

vue/frontend/src/components/MainPageForm.vue

fix2: [진건오] 메인페이지 상품 매핑 이슈 [DIY-SALES-WEB-UI 17]

---

vue/frontend/src/components/shoppingCart/ShoppingCartForm.vue

style: [진건오] 장바구니 페이지 [DIY-SALES-WEB-UI 38]

---

vue/frontend/src/components/product/ProductReadForm.vue

fix: [김소연] 일반회원/비회원이 상품을 클릭했을 때 보여지는 상품페이지의 판매정보 UI [DIY-SALES-WEB-UI 14]

---

vue/frontend/package.json
vue/frontend/src/components/buyerMyPage/BuyerOrderInfoPageForm.vue
vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue
vue/frontend/src/components/buyerMyPage/RecentlyViewedProductFrom.vue
vue/frontend/src/components/product/search/SearchForm.vue
vue/frontend/src/components/seller/ProductManageForm.vue
vue/frontend/src/views/product/ProductReadView.vue

fix: [진건오] 일반회원 최근 본 상품 [DIY-SALES-WEB-UI 79]

---

spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/qna/QnA.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/product/review/Review.java

**완료**
✅ 문의 본문 / 답변 본문 / 후기 본문 글자 수 제한 500자로 걸어놓도록 엔티티 수정

feat: [조안나] 문의/후기 본문,답변 글자 수 500자로 제한[DIY-SALES-PROCESS 58]

---

vue/frontend/src/App.vue

- 마이페이지 최초 접속 시 내 정보 페이지로 이동하도록 변경

update2: [진건오] 마이페이지 접속 시 이동 페이지 변경 [DIY-SALES-WEB-UI 29]

---

vue/frontend/src/store/actions.js

- 판매자 로그인 시 판매자 마이페이지에 HOME으로 이동하도록 변경

update2: 판매자 로그인 후 바로 연결되는 판매자 Home페이지 UI [DIY-SALES-WEB-UI 88]

---

vue/frontend/src/components/shoppingCart/ShoppingCartForm.vue

- 장바구니 페이지 처음 접속 시 모든 상품에 체크가 되어버린경우
→ 체크가 되어있어도 총금액에 표시되지 않는 이슈

fix3: 장바구니 체크 설정 번경[DIY-SALES-WEB-UI 38]

---

vue/frontend/src/components/buyerMyPage/BuyerOrderInfoPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue

일반회원 구매후기 등록 타이틀 리뷰 작성 → 후기 작성으로 변경
일반회원 후기 등록시 글자수 제한 500자 + 글자수체크
**변경사항**
BuyerOrderInfoPageForm
OrderDetailForm

style: [김소연] 일반회원 사용자가 최근 주문내역에서 상품에 대한 리뷰를 작성할 수 있는 UI[DIY-SALES-WEB-UI 51]

---

vue/frontend/src/components/buyerMyPage/BuyerMyPageTopNav.vue
vue/frontend/src/store/states.js

- 상단 내비게이션에 각각 내역 개수들이 보여지는 숫자를 클릭했을 때
해당 내역 페이지로 이동하도록 설정

update3: 마이페이지 상단 내비게이션 각 페이지 라우터 연결[DIY-SALES-WEB-UI 29]

---

vue/frontend/src/components/buyerMyPage/BuyerReviewForm.vue

변경사항
일반회원 후기 수정 버튼 눌렀을 때 글자수 제한(500) + 글자수체크
**BuyerReviewForm**

style: [김소연] 일반회원이 마이리뷰페이지에서 본인이 작성한 리뷰를 수정할 수 있는 페이지[DIY-SALES-WEB-UI 77]

---

flutter/buy_idea/lib/api/ip_info.dart
flutter/buy_idea/lib/api/seller/spring_seller_info_api.dart
flutter/buy_idea/lib/api/seller/spring_seller_order_api.dart
flutter/buy_idea/lib/api/seller/spring_seller_product_api.dart
flutter/buy_idea/lib/api/seller/spring_seller_qna_api.dart
flutter/buy_idea/lib/api/seller/spring_seller_total_api.dart
flutter/buy_idea/lib/api/spring_favorite_api.dart
flutter/buy_idea/lib/api/spring_member_api.dart
flutter/buy_idea/lib/api/spring_my_info_api.dart
flutter/buy_idea/lib/api/spring_order_api.dart
flutter/buy_idea/lib/api/spring_product_api.dart
flutter/buy_idea/lib/api/spring_qna_api.dart
flutter/buy_idea/lib/api/spring_review_api.dart
flutter/buy_idea/lib/api/spring_shopping_bucket_api.dart
flutter/buy_idea/lib/component/buyer/app_bar/bottom_bar.dart

**완료**
✅ Http Uri static  변수로 관리하도록 수정
✅ 메인 바텀네비게이션 UI 수정

feat: [조안나] API 요청시 httpUri IP주소 static변수 하나로 관리하는 시스템 [DIY-SALES-APP-UI 135]

---

flutter/buy_idea/lib/api/spring_order_api.dart
flutter/buy_idea/lib/api/spring_shopping_bucket_api.dart
flutter/buy_idea/lib/component/buyer/product/product_buy_and_shopping_cart_select_modal_sheet.dart
flutter/buy_idea/lib/component/buyer/shopping_bucket/shopping_bucket_form.dart
flutter/buy_idea/lib/component/buyer/shopping_bucket/shopping_controller.dart
flutter/buy_idea/lib/component/buyer/shopping_bucket/total_price_bottom.dart
flutter/buy_idea/lib/pages/buyer/main_page.dart
flutter/buy_idea/lib/pages/buyer/order/order_page.dart

**완료**
✅ 장바구니 삭제 요청 API 
✅ 결제완료 후 페이지 이동 
✅ 결제완료 후 결제한 상품 장바구니 삭제 시스템

feat: [조안나] 일반회원이 상품 결제가 완료됐을 때 담아뒀던 장바구니를 비워주는 시스템[DIY-SALES-APP-UI 67]

---

vue/frontend/src/store/actions.js

fix: [김소연] 일반회원이 마이리뷰페이지에서 작성한 리뷰를 수정할 수 있는 수정 페이지[DIY-SALES-WEB-UI 77]

---

flutter/buy_idea/lib/pages/buyer/product/product_details_page.dart

fix
- 비회원일 때 nickname값이 null되어 전구 UI가 나타나지않아 해당 로직 수정

fix: [박선호] 상품 상세페이지에서 일반회원이 찜할 수 있는 전구버튼 UI [DIY-SALES-APP-UI 131]

---

vue/frontend/src/views/productByCategory/HandmadeCategoryView.vue
vue/frontend/src/views/productByCategory/HobbyCategoryView.vue
vue/frontend/src/views/productByCategory/KnowhowCategoryView.vue

- 상단 필터 목록 중 어떤 필터를 눌렀는지 보여주는 텍스트UI 삭제

style: [진건오] 카테고리 페이지 [DIY-SALES-WEB-UI 48]

---

vue/frontend/src/router/index.js

feat: [진건오] 스크롤이 항상 맨위에 위치하도록 하는 시스템 [DIY-SALES-WEB-UI 96]

---

vue/frontend/src/components/account/CommonSignUpForm.vue

fix: [김소연] 일반회원용모드를 선택한 사용자가 가입하기 위한 회원가입페이지 UI [DIY-SALES-WEB-UI 3]

---

vue/frontend/src/App.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/mutations.js

- 키워드를 넣지 않은 상태에서 검색할 때 이전 키워드로 검색한 상품이 남아있는 이슈
→ 해결

fix: [진건오] 검색 페이지 [DIY-SALES-WEB-UI 55]

---

vue/frontend/src/components/buyerMyPage/BuyerAccountDropForm.vue

fix: [김소연] 회원가입되어있는 사용자가 회원탈퇴를 하기 위한 회원탈퇴 페이지UI[DIY-SALES-WEB-UI 28]

---

vue/frontend/src/components/productByCategory/HandmadeProductByCategoryForm.vue
vue/frontend/src/components/productByCategory/HobbyProductByCategoryForm.vue
vue/frontend/src/components/productByCategory/KnowHowProductByCategoryForm.vue
vue/frontend/src/store/actions.js
vue/frontend/src/store/mutations.js
vue/frontend/src/views/productByCategory/HandmadeCategoryView.vue
vue/frontend/src/views/productByCategory/HobbyCategoryView.vue
vue/frontend/src/views/productByCategory/KnowhowCategoryView.vue

- 후기순으로 보았을 때 같은 후기가 2번씩 들어오는 이슈로 재설계
- 상품을 보고 뒤로가기 버튼을 통해 다시 돌아왔을 때 상품이 중복되서 저장되는 이슈로 재설계

fix3: [진건오] 필터 시스템 [DIY-SALES-WEB-UI 91]

---

vue/frontend/src/store/actions.js
vue/frontend/src/store/mutations.js

- 로그아웃해도 로그인 했던 사용자 정보가 남아있는 이슈

fix2: [진건오] 로그아웃 [DIY-SALES-WEB-UI 6]

---

vue/frontend/src/components/buyerMyPage/BuyerOrderInfoPageForm.vue
vue/frontend/src/components/buyerMyPage/OrderDetailForm.vue
vue/frontend/src/views/buyerMyPage/BuyerInfoView.vue

feat: [임재범] 구매자 주문정보 페이지에서 상품을 순서대로 정렬하는 시스템 [DIY-SALES-WEB-UI 97]

---

spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucket.java
spring/buy_idea/src/main/java/team_project/buy_idea/entity/order/shoppingBucket/ShoppingBucketItem.java

- 회원탈퇴 하려는 사용자의 장바구니 기능 사용 후 회원탈퇴 시 탈퇴가 되지 않는 이슈
-> 해결

fix: [진건오] 회원탈퇴 시스템[DIY-SALES-PROCESS 14]

---

flutter/buy_idea/lib/component/buyer/my_info/my_order_info/review/my_review_form.dart

fix: [박선호] 일반회원이 마이페이지의 ‘나의 후기’ 버튼 클릭 시 본인이 등록한 구매 후기 리스트가 보여지는 페이지 UI [DIY-SALES-APP-UI 97]

---

spring/buy_idea/src/main/java/team_project/buy_idea/controller/order/shoppingBucket/request/ShoppingBucketDeleteItemRequest.java

fix2: [진건오] 장바구니 상품 삭제 시스템 누락파일[DIY-SALES-PROCESS 24]

---

spring/buy_idea/src/main/java/team_project/buy_idea/service/member/MemberServiceImpl.java

- 닉네임 변경시 해당 닉네임으로 작성된 review, qna 또 주문내역의 데이터들을 가져올 수 있도록 코드 변경

fix: [진건오]일반회원 닉네임 변경 [DIY-SALES-PROCESS 13]

---

spring/buy_idea/.env
spring/buy_idea/Dockerfile
spring/buy_idea/docker-compose.yml
spring/buy_idea/docker/mysql/custom.cnf
spring/buy_idea/src/main/resources/application.yaml

- application.yaml 변경있습니다
- env 파일만 수정하시면 됩니다

feat: [진건오]배포 설정 [DIY-SALES-PROCESS 59]
